version: "3.8"
services:
  front:
    image: node:17-alpine3.13
    command: sh -c 'npm run dev'
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - "./front:/front"
    working_dir: /front
  postgres:
    image: postgres:14-alpine
    restart: always
    tty: true
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:latest
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    env_file:
      - .env
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
volumes:
  db_data:
