import type { NextPage } from 'next';
import Head from 'next/head';
import { TodoForm } from '../../components/TodoForm';
import { useTodos } from './useTodos';

const Todo: NextPage = () => {
  const { data, loading, onClickDeleteTodo } = useTodos();

  if (loading) {
    return (
      <div className='bg-stone-50 flex justify-center min-h-screen items-center'>
        <div className='animate-spin h-10 w-10 border-4 border-blue-500 rounded-full border-t-transparent'></div>
      </div>
    );
  }

  return (
    <div className='text-center bg-stone-50 min-h-screen'>
      <Head>
        <title>Sample Todo App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1 className='text-2xl mt-10 inline-block'>Todo app</h1>
      <TodoForm />
      {data && (
        <div className='mt-2 grid grid-cols-3'>
          {data.todos.map((todo) => (
            <div key={todo.id} className='m-6 bg-slate-100 border-2 p-2'>
              <button
                className='bg-slate-600 hover:bg-slate-500 text-white p-1 m-1'
                onClick={() => onClickDeleteTodo(todo.id)}
              >
                削除
              </button>
              <button className='bg-slate-600 hover:bg-slate-500 text-white p-1 m-1'>更新</button>
              <p>{todo.title}</p>
              <p>{todo.description}</p>
              <p>{todo.created_at}</p>
              <p>{todo.updated_at}</p>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default Todo;
