import type { NextPage } from 'next';
import Head from 'next/head';
import { useGetTodosQuery, useGetTodosByPkQuery } from '../../generated/graphql';

const Todo: NextPage = () => {
  const param = {
    id: 1,
  };
  const { data, loading, error } = useGetTodosQuery();
  // const { data, loading, error } = useGetTodosByPkQuery({
  //   variables: {
  //     id: 10,
  //   },
  // });

  return (
    <div className='text-center bg-stone-50 min-h-screen'>
      <Head>
        <title>Sample Todo App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1 className='text-2xl mt-10 inline-block'>Todo app</h1>
      {data && (
        <div className='mt-2'>
          {/* <p>{data.todos_by_pk?.title}</p>
          <p>{data.todos_by_pk?.description}</p>
          <p>{data.todos_by_pk?.created_at}</p>
          <p>{data.todos_by_pk?.updated_at}</p> */}
          {data.todos.map(({ id, title, description, created_at, updated_at }) => (
            <div key={id} className='m-6'>
              <p>{title}</p>
              <p>{description}</p>
              <p>{created_at}</p>
              <p>{updated_at}</p>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default Todo;
