import Head from 'next/head';
import { Spinner } from '../../../components/ui/Spinner';
import { TodoCard } from '../../../components/ui/TodoCard';
import { TodoForm } from '../../../components/ui/TodoForm';
import { useTodos } from './Todo.hooks';

export const Todo = () => {
  const { data, loading } = useTodos();

  if (loading) {
    return <Spinner />;
  }

  return (
    <div className='text-center bg-stone-50 min-h-screen'>
      <Head>
        <title>Sample Todo App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <h1 className='text-2xl mt-10 inline-block'>Todo app</h1>
        <TodoForm mode='add' />
        {data && (
          <div className='mt-2 grid grid-cols-3'>
            {data.todos.map((todo) => (
              <TodoCard key={todo.id} {...todo} />
            ))}
          </div>
        )}
      </main>
    </div>
  );
};
