import type { NextPage } from 'next';
import Head from 'next/head';
import Profile from '../components/Profile/Profile';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <h1 className='text-3xl font-bold underline'>Hello world!</h1>
        <a href='/api/auth/login'>Login</a>
        <a href='/api/auth/logout'>Logout</a>
        <Profile />
      </main>
    </div>
  );
};

export default Home;
