import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <div className='bg-stone-50 min-h-screen text-center'>
          <h1 className='text-3xl mt-10 inline-block'>Next.js and Hasura Sample app</h1>
          <ul className='mt-4'>
            サンプル機能
            <li className='mt-2'>
              <Link href='/todo'>Todoアプリ</Link>
            </li>
          </ul>
        </div>
      </main>
    </div>
  );
};

export default Home;
