import type { NextPage } from 'next';
import Head from 'next/head';
import { Spinner } from '../../../components/Spinner';
import { TodoForm } from '../../../components/TodoForm';
import { useTodoId } from './useTodoId';

const TodoId: NextPage = () => {
  const { updateItem, loading } = useTodoId();
  if (loading) {
    return <Spinner />;
  }
  return (
    <div className='text-center bg-stone-50 min-h-screen'>
      <Head>
        <title>Todo 編集</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <h1 className='text-2xl mt-10 inline-block'>Todo 編集</h1>
        <TodoForm mode='update' updateItem={updateItem} />
      </main>
    </div>
  );
};

export default TodoId;
